import 'package:intl/intl.dart';

import '../../data/models/road_session.dart';

class AppDateTime {
  static final DateFormat _sessionFormat = DateFormat('dd MMM yyyy • HH:mm');
  static final DateFormat _detailFormat = DateFormat('dd MMM yyyy • HH:mm:ss');
  static final DateFormat _titleFormat = DateFormat('yyyy-MM-dd HH:mm');
  static final DateFormat _shortFormat = DateFormat('dd MMM • HH:mm');
  static final RegExp _generatedTripTitlePattern =
      RegExp(r'^Road Trip \d{4}-\d{2}-\d{2}( \d{2}:\d{2})?$');

  static DateTime nowUtc() => DateTime.now().toUtc();

  static DateTime parseServer(String? value, {DateTime? fallback}) {
    if (value == null || value.trim().isEmpty) {
      return (fallback ?? DateTime.now()).toLocal();
    }

    final parsed = DateTime.tryParse(value);
    if (parsed == null) {
      return (fallback ?? DateTime.now()).toLocal();
    }

    return parsed.toLocal();
  }

  static String formatSession(DateTime? value) {
    if (value == null) return '--';
    return _sessionFormat.format(value.toLocal());
  }

  static String formatDetailed(DateTime? value) {
    if (value == null) return '--';
    return _detailFormat.format(value.toLocal());
  }

  static String formatShort(DateTime? value) {
    if (value == null) return '--';
    return _shortFormat.format(value.toLocal());
  }

  static String autoTripTitle({DateTime? value}) {
    final local = (value ?? DateTime.now()).toLocal();
    return 'Road Trip ${_titleFormat.format(local)}';
  }

  static bool isAutoGeneratedTripTitle(String title) {
    return _generatedTripTitlePattern.hasMatch(title.trim());
  }

  static String displaySessionTitle(RoadSession session) {
    if (isAutoGeneratedTripTitle(session.title)) {
      return autoTripTitle(value: session.startTime);
    }

    return session.title;
  }
}
